output-format: pylint
strictness: veryhigh
autodetect: false

ignore-paths:
  - venv
  - __pycache__

bandit:
  run: true

dodgy:
  run: false

pylint:
  enable:
    - useless-suppression
  options:
    max-line-length: 120

pycodestyle:
  options:
    max-line-length: 120